kind: pipeline
name: default

clone:
  depth: 1

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: cargo-update
  image: rust
  commands:
  - cargo update

- name: fmt-check
  image: rust
  commands:
  - rustup component add rustfmt
  - cargo fmt --verbose --all -- --check

- name: clippy-check
  image: rust
  commands:
  - rustup component add clippy
  - cargo clippy

- name: tests
  image: rust
  commands:
  - cargo test --verbose $FEATURES -- --nocapture
