language: rust
matrix:
    fast_finish: true
    include:
        - rust: beta
        - rust: stable

sudo: false
         
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo check
  - cargo fmt --verbose --all -- --check
  - cargo clippy
  - cargo test --doc --verbose $FEATURES -- --nocapture
  - cargo test --verbose $FEATURES -- --nocapture

addons:
  apt:
    packages:
      - libssl-dev

notifications:
email: false

